excerpt_separator: ""
highlighter: pygments
markdown: kramdown
url: http://maurodoglio.github.io
title: maurodoglio.com
tagline: A blog about snakes, dinosaurs and unicorns
description: This is the personal blog post of Mauro Doglio.
paginate: 10
comments: true

# Settings for google analytics
ga_tracking_id : 'UA-30883241-1'

gems:
  - jemoji
  - jekyll-mentions
